name: MorePorts
version: '${project.version}'
main: com.epixdevelopment.moreports.MorePorts
api-version: '1.21'
description: A plugin to listen on multiple ports
authors: [Rennex]

permissions:
  moreports.admin:
    description: Allows managing MorePorts
    default: op

commands:
  moreports:
    description: Manage MorePorts
    permission: moreports.admin
    usage: /moreports [reload|status]
